apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: fabiocaettano74/api-cadastro-usuario:v3
          ports:
          - containerPort: 3003
            name: http
          - containerPort: 443
            name: https
          imagePullPolicy: Always
          env:
            - name: Mongo__User
              value: mongouser
            - name: Mongo__Password
              value: mongopwd
            - name: Mongo__Host
              value: service-mongo
            - name: Mongo__Port
              value: "27017"
            - name: Mongo__Database
              value: DBTest