apiVersion: v1
kind: Service
metadata:
  name: service-api
spec:
  selector:
    app: api
  ports:
  - port: 8080
    targetPort: 3003
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: NodePort